version: '3'
services:
  # openresty:
  #   # image: ${OPENRESTY_IMAGE_BASE}:${OPENRESTY_IMAGE_TAG}
  #   image: ${OPENRESTY_CHINA_IMAGE_BASE}:${OPENRESTY_IMAGE_TAG}
  #   ports:
  #     - "${NGINX_HTTP_HOST_PORT}:80"
  #     - "${NGINX_HTTPS_HOST_PORT}:443"
  #     - "8001:8001"
  #     - "8072:8072"
  #     - "8074:8074"
  #     - "8004:8004"
  #   volumes:
  #     - ${NGINX_CONF_FILE}:/usr/local/openresty/nginx/conf/nginx.conf
  #     - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
  #     - ${NGINX_LOG_DIR}:/var/log/nginx
  #     - ${SOURCE_SHARE_DIR}:/var/www
  #     - ${OPENRESTY_LUA_DIR}:/usr/local/openresty/nginx/conf/lua
  #     - ${NGINX_SSL_DIR}:/etc/letsencrypt
  #   restart: always
  #   environment:
  #     TZ: "$TZ"
  #   container_name: ${OPENRESTY_CONTAINER_NAME}
  #   networks:
  #       - backend

  nginx:
    image: ${NGINX_IMAGE_BASE}:${NGINX_IMAGE_TAG}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
      - "8001:8001"
      - "8072:8072"
      - "8074:8074"
      - "8004:8004"
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ${SOURCE_SHARE_DIR}:/var/www
      - ${NGINX_SSL_DIR}:/etc/letsencrypt
    restart: always
    environment:
        TZ: "${TZ}"
    container_name: ${NGINX_CONTAINER_NAME}
    networks:
        - backend

  php74:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP74_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP74_EXTENSIONS}
        TZ: "$TZ"
    ports:
      - "9074:9000"
      - "9073:9073"
    volumes:
      - ${SOURCE_SHARE_DIR}:/var/www
      - ${PHP_INI_FILE}:/usr/local/etc/php/php.ini
      - ${PHP_WWW_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
      - ${PHP_LOG_DIR}:/var/log/php
    networks:
      - backend
    container_name: ${PHP74_CONTAINER_NAME}

  php81:
    build:
      context: ./services/php8
      args:
        PHP_VERSION: php:${PHP81_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP81_EXTENSIONS}
        TZ: "$TZ"
    ports:
      - "9100:9100"
      - "8117:8187"
      - "8119:8189"
      - "8118:8788"
    volumes:
      - ${SOURCE_SHARE_DIR}:/var/www
      - ${PHP_INI_FILE}:/usr/local/etc/php/php.ini
      - ${PHP_WWW_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
      - ${PHP_LOG_DIR}:/var/log/php
    networks:
      - backend
    container_name: ${PHP81_CONTAINER_NAME}

  # php72:
  #   build:
  #     context: ./services/php
  #     args:
  #       PHP_VERSION: php:${PHP72_VERSION}-fpm-alpine
  #       CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
  #       PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
  #       TZ: "$TZ"
  #   ports:
  #     - "9072:9000"
  #     - "9502:9502"
  #     - "9503:9503"
  #   volumes:
  #     - ${SOURCE_SHARE_DIR}:/var/www
  #     - ${PHP_INI_FILE}:/usr/local/etc/php/php.ini
  #     - ${PHP_WWW_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
  #     - ${PHP_LOG_DIR}:/var/log/php
  #   networks:
  #     - backend
  #   container_name: ${PHP72_CONTAINER_NAME}

  # php56:
  #   build:
  #     context: ./services/php
  #     args:
  #       PHP_VERSION: php:${PHP56_VERSION}-fpm-alpine
  #       CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
  #       PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
  #       TZ: "$TZ"
  #   ports:
  #     - "9056:9000"
  #   volumes:
  #     - ${SOURCE_SHARE_DIR}:/var/www
  #     - ${PHP_INI_FILE}:/usr/local/etc/php/php.ini
  #     - ${PHP_WWW_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
  #     - ${PHP_LOG_DIR}:/var/log/php
  #   networks:
  #     - backend
  #   container_name: ${PHP56_CONTAINER_NAME}

  mysql:
    image: mysql:${MYSQL_IMAGE_TAG}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    hostname: dnmp-mysql
    ports:
      - "3308:3306"
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_CONF_FILE}:/etc/mysql/my.cnf
      # - ${MYSQL_CONF_FILE}:/etc/mysql/mysql.cnf # 8.0 配置
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        TZ: "$TZ"
    networks:
      - backend
    container_name: ${MYSQL_CONTAINER_NAME}

  # mariadb:
  #   image: ${MariaDB_IMAGE_BASE}:${MariaDB_IMAGE_TAG}
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   hostname: ${MariaDB_CONTAINER_NAME}
  #   ports:
  #     - "3309:3306"
  #   volumes:
  #     - ${MariaDB_DATA_DIR}:/var/lib/mysql
  #     - ${MariaDB_CONF_FILE}:/etc/mysql/my.cnf
  #   environment:
  #       MYSQL_ROOT_PASSWORD: 123456
  #       TZ: "$TZ"
  #   networks:
  #     - backend
  #   container_name: ${MariaDB_CONTAINER_NAME}

  redis:
    image: redis:${REDIS_IMAGE_TAG}
    hostname: dnmp-redis
    ports:
      - "${REDIS_HOST_PORT}:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - backend
    volumes:
      - ${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf
      - ${REDIS_DATA_DIR}:/data
    restart: always
    container_name: ${REDIS_CONTAINER_NAME}

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:${PHPMYADMIN_TAG}
  #   ports:
  #     - "${PHPMYADMIN_HOST_PORT}:80"
  #   networks:
  #     - backend
  #   environment:
  #     - PMA_HOST=dnmp-mysql
  #     - PMA_PORT=3306
  #     - TZ=$TZ
  #   container_name: dnmp-phpmyadmin

  # rabbitmq:
  #   image: rabbitmq:${RABBITMQ_VERSION}
  #   restart: always
  #   ports:
  #     - "${RABBITMQ_HOST_PORT_CLIENT}:5672"
  #     - "${RABBITMQ_HOST_PORT_MANAGEMENT}:15672"
  #   environment:
  #     TZ: "$TZ"
  #     RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
  #     RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
  #   container_name: ${RABBITMQ_CONTAINER_NAME}
  #   networks:
  #     - backend

  # 单机模式
  # nacos:
  #   # build:
  #   #   context: ./services/nacos
  #   image: nacos/nacos-server:1.4.0
  #   ports:
  #     - "8848:8848"
  #   volumes:
  #     - ./log/nacos:/home/nacos/logs
  #     - ./services/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
  #   networks:
  #     - backend
  #   container_name: dnmp-nacos
  #   env_file:
  #     - ./services/nacos/env/nacos-standlone-mysql.env

  # 集群模式
  # nacos1:
  #   image: nacos/nacos-server:1.4.0
  #   ports:
  #     - "8848:8848"
  #   volumes:
  #     - ./log/nacos:/home/nacos/logs
  #     - ./services/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
  #   networks:
  #     - backend
  #   container_name: dnmp-nacos1
  #   env_file:
  #     - ./services/nacos/env/nacos-hostname.env

  # nacos2:
  #   image: nacos/nacos-server:1.4.0
  #   ports:
  #     - "8849:8848"
  #   volumes:
  #     - ./log/nacos:/home/nacos/logs
  #     - ./services/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
  #   networks:
  #     - backend
  #   container_name: dnmp-nacos2
  #   env_file:
  #     - ./services/nacos/env/nacos-hostname.env

  # nacos3:
  #   image: nacos/nacos-server:1.4.0
  #   ports:
  #     - "8850:8848"
  #   volumes:
  #     - ./log/nacos:/home/nacos/logs
  #     - ./services/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
  #   networks:
  #     - backend
  #   container_name: dnmp-nacos3
  #   env_file:
  #     - ./services/nacos/env/nacos-hostname.env

networks:
  backend:
    driver: bridge
